### Contents

**Analysis**

**Preprocessing**

**Creating Random Forest Classifier**

**Evaluating Training and Testing set**

**Creating Support Vector Classifier**

**Evaluating Training and Testing set**

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['weatherAUS.csv']


In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
dataset = pd.read_csv('../input/weatherAUS.csv')

In [4]:
dataset.head()

Date Location  MinTemp      ...       RainToday  RISK_MM  RainTomorrow
0  2008-12-01   Albury     13.4      ...              No      0.0            No
1  2008-12-02   Albury      7.4      ...              No      0.0            No
2  2008-12-03   Albury     12.9      ...              No      0.0            No
3  2008-12-04   Albury      9.2      ...              No      1.0            No
4  2008-12-05   Albury     17.5      ...              No      0.2            No

[5 rows x 24 columns]

In [5]:
dataset.isnull().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64

In [6]:
dataset.shape

(142193, 24)

In [7]:
dataset.drop(labels = ['Date','Location','Evaporation','Sunshine','Cloud3pm','Cloud9am','RISK_MM'],axis = 1,inplace = True)

In [8]:
dataset.head()

MinTemp  MaxTemp  Rainfall     ...      Temp3pm  RainToday RainTomorrow
0     13.4     22.9       0.6     ...         21.8         No           No
1      7.4     25.1       0.0     ...         24.3         No           No
2     12.9     25.7       0.0     ...         23.2         No           No
3      9.2     28.0       0.0     ...         26.5         No           No
4     17.5     32.3       1.0     ...         29.7         No           No

[5 rows x 17 columns]

In [9]:
dataset['RainToday'].replace({'No':0,'Yes':1},inplace = True)
dataset['RainTomorrow'].replace({'No':0,'Yes':1},inplace = True)
dataset.shape

(142193, 17)

In [10]:
dataset.dropna(inplace = True)

In [11]:
dataset.shape

(112925, 17)

In [12]:
categorical = ['WindGustDir','WindDir9am','WindDir3pm']

In [13]:
dataset = pd.get_dummies(dataset,columns = categorical,drop_first=True)

In [14]:
dataset.head()

MinTemp  MaxTemp       ...        WindDir3pm_WNW  WindDir3pm_WSW
0     13.4     22.9       ...                     1               0
1      7.4     25.1       ...                     0               1
2     12.9     25.7       ...                     0               1
3      9.2     28.0       ...                     0               0
4     17.5     32.3       ...                     0               0

[5 rows x 59 columns]

In [15]:
dataset.shape

(112925, 59)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
sc = StandardScaler()

In [18]:
x = dataset.drop(labels = ['RainTomorrow'],axis = 1)

In [47]:
x.shape

(112925, 58)

In [19]:
y = dataset['RainTomorrow']

In [20]:
x = sc.fit_transform(x)

/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype uint8, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/opt/conda/lib/python3.6/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype uint8, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [21]:
x

array([[ 0.11756741, -0.10822071, -0.20666127, ..., -0.27515781,
         3.90999267, -0.27186642],
       [-0.84180219,  0.20684494, -0.27640495, ..., -0.27515781,
        -0.25575496,  3.67827705],
       [ 0.03761995,  0.29277194, -0.27640495, ..., -0.27515781,
        -0.25575496,  3.67827705],
       ...,
       [-1.44940294,  0.23548728, -0.27640495, ..., -0.27515781,
        -0.25575496, -0.27186642],
       [-1.16159206,  0.46462594, -0.27640495, ..., -0.27515781,
         3.90999267, -0.27186642],
       [-0.77784422,  0.4789471 , -0.27640495, ..., -0.27515781,
        -0.25575496, -0.27186642]])

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 40)

## Random Forest Classifier

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
rc = RandomForestClassifier(n_estimators = 200,max_leaf_nodes = 1000)
rc.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=1000,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [25]:
y_pred = rc.predict(x_test)

In [26]:
y_train_pred = rc.predict(x_train)

In [27]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

## Training set evaluation

In [28]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.88      0.98      0.93     70398
           1       0.87      0.54      0.67     19942

   micro avg       0.88      0.88      0.88     90340
   macro avg       0.88      0.76      0.80     90340
weighted avg       0.88      0.88      0.87     90340



In [29]:
confusion_matrix(y_train,y_train_pred)

array([[68850,  1548],
       [ 9186, 10756]])

## Testing set evaluation

In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91     17508
           1       0.78      0.45      0.57      5077

   micro avg       0.85      0.85      0.85     22585
   macro avg       0.82      0.71      0.74     22585
weighted avg       0.84      0.85      0.83     22585



In [31]:
print(confusion_matrix(y_test,y_pred))

[[16868   640]
 [ 2783  2294]]


In [32]:
print('Training accuracy ---->',accuracy_score(y_train,y_train_pred))
print('Testing accuracy  ---->',accuracy_score(y_test,y_pred))

Training accuracy ----> 0.8811822005756033
Testing accuracy  ----> 0.848439229577153


## Support Vector Classification

In [33]:
from sklearn.svm import SVC

In [34]:
svc = SVC()

In [35]:
svc.fit(x_train,y_train)

/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [36]:
y_pred = svc.predict(x_test)
y_train_pred = svc.predict(x_train)

## Training Set Evaluation

In [37]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92     70398
           1       0.82      0.52      0.64     19942

   micro avg       0.87      0.87      0.87     90340
   macro avg       0.85      0.75      0.78     90340
weighted avg       0.87      0.87      0.86     90340



In [38]:
confusion_matrix(y_train,y_train_pred)

array([[68127,  2271],
       [ 9506, 10436]])

## Testing Set Evaluation

In [39]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91     17508
           1       0.78      0.48      0.59      5077

   micro avg       0.85      0.85      0.85     22585
   macro avg       0.82      0.72      0.75     22585
weighted avg       0.84      0.85      0.84     22585



In [40]:
confusion_matrix(y_test,y_pred)

array([[16813,   695],
       [ 2648,  2429]])

In [41]:
print('Training Accuracy ---->',accuracy_score(y_train,y_train_pred))
print('Testing Accuracy  ---->',accuracy_score(y_test,y_pred))

Training Accuracy ----> 0.869636927164047
Testing Accuracy  ----> 0.8519814035864511


## ANN

In [44]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [45]:
classifier = Sequential()

In [51]:
classifier.add(Dense(units = 30,kernel_initializer='uniform',activation = 'relu',input_dim = 58))
classifier.add(Dense(units = 30,kernel_initializer='uniform',activation = 'relu'))
classifier.add(Dense(units = 30,kernel_initializer='uniform',activation = 'relu'))
classifier.add(Dense(units = 1,activation='sigmoid',kernel_initializer='uniform'))

Instructions for updating:
Colocations handled automatically by placer.


In [52]:
classifier.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [54]:
classifier.fit(x_train,y_train,epochs = 50,batch_size=10)

Epoch 1/50
90340/90340 [==============================] - 40s 438us/step - loss: 0.3439 - acc: 0.8513
Epoch 2/50
90340/90340 [==============================] - 39s 432us/step - loss: 0.3392 - acc: 0.8543
Epoch 3/50
90340/90340 [==============================] - 39s 432us/step - loss: 0.3364 - acc: 0.8559
Epoch 4/50
90340/90340 [==============================] - 39s 430us/step - loss: 0.3336 - acc: 0.8570
Epoch 5/50
90340/90340 [==============================] - 39s 432us/step - loss: 0.3319 - acc: 0.8574
Epoch 6/50
90340/90340 [==============================] - 39s 431us/step - loss: 0.3304 - acc: 0.8579
Epoch 7/50
90340/90340 [==============================] - 39s 428us/step - loss: 0.3291 - acc: 0.8584
Epoch 8/50
90340/90340 [==============================] - 39s 428us/step - loss: 0.3277 - acc: 0.8586
Epoch 9/50
90340/90340 [==============================] - 39s 430us/step - loss: 0.3266 - acc: 0.8589
Epoch 10/50
90340/90340 [==============================] - 38s 426us/step - loss: 

In [68]:
y_pred = classifier.predict_classes(x_test)
y_train_pred = classifier.predict_classes(x_train)

In [69]:
print('Training Accuracy ---->',accuracy_score(y_train,y_train_pred))
print('Testing Accuracy  ---->',accuracy_score(y_test,y_pred))

Training Accuracy ----> 0.8697808279831747
Testing Accuracy  ----> 0.8490591100287802
