Ok! It's time to find out if we can say that the historical data from the São Paulo championship football have passed the validation of Benford's Law

I have applied the Benford's Law for all numerical information available in the dataset (Points, Matches, Won, Drawn, Lost, Goals_For, Goals_Against, Goal_Difference, Participations), but I have not test the information "Champion" because only few teams have won the campionship

I have consided alpha=0.05 to determine if the information have passed the validation or not.

Let's get started

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

## Import campeonato_paulista_ranking_historico data

In [ ]:
df = pd.read_csv('/kaggle/input/benford-law-in-football/campeonato_paulista_ranking_historico.csv', encoding = 'latin-1', sep=';')
df.head()

## Install benfordslaw

In [ ]:
pip install benfordslaw

In [ ]:
# Initialize
from benfordslaw import benfordslaw
bl = benfordslaw(alpha=0.05)

In [ ]:
# Extract Points information.
X = df['Points'].loc[df['Points']>0].values

# Print
print(X)
# array([ 5387, 23618,  1710, ...,    16,    21,     0], dtype=int64)

# Make fit
results = bl.fit(X)

# Plot
bl.plot(title="Benford's Law for Points")

In [ ]:
# Extract Matches information.
X = df['Matches'].loc[df['Matches']>0].values

# Print
print(X)
# array([ 5387, 23618,  1710, ...,    16,    21,     0], dtype=int64)

# Make fit
results = bl.fit(X)

# Plot
bl.plot(title="Benford's Law for Matches")

In [ ]:
# Extract Won information.
X = df['Won'].loc[df['Won']>0].values

# Print
print(X)
# array([ 5387, 23618,  1710, ...,    16,    21,     0], dtype=int64)

# Make fit
results = bl.fit(X)

# Plot
bl.plot(title="Benford's Law for Won")

In [ ]:
# Extract Drawn information.
X = df['Drawn'].loc[df['Drawn']>0].values

# Print
print(X)
# array([ 5387, 23618,  1710, ...,    16,    21,     0], dtype=int64)

# Make fit
results = bl.fit(X)

# Plot
bl.plot(title="Benford's Law for Drawn")

In [ ]:
# Extract Lost information.
X = df['Lost'].loc[df['Lost']>0].values

# Print
print(X)
# array([ 5387, 23618,  1710, ...,    16,    21,     0], dtype=int64)

# Make fit
results = bl.fit(X)

# Plot
bl.plot(title="Benford's Law for Lost")

In [ ]:
# Extract Goals_For information.
X = df['Goals_For'].loc[df['Goals_For']>0].values

# Print
print(X)
# array([ 5387, 23618,  1710, ...,    16,    21,     0], dtype=int64)

# Make fit
results = bl.fit(X)

# Plot
bl.plot(title="Benford's Law for Goals_For")

In [ ]:
# Extract Goals_Against information.
X = df['Goals_Against'].loc[df['Goals_Against']>0].values

# Print
print(X)
# array([ 5387, 23618,  1710, ...,    16,    21,     0], dtype=int64)

# Make fit
results = bl.fit(X)

# Plot
bl.plot(title="Benford's Law for Goals_Against")

In [ ]:
# Extract Goals_Difference information.
X = df['Goals_Difference'].loc[df['Goals_Difference']!=0].values

# Print
print(X)
# array([ 5387, 23618,  1710, ...,    16,    21,     0], dtype=int64)

# Make fit
results = bl.fit(X)

# Plot
bl.plot(title="Benford's Law for Goals_Difference")

In [ ]:
# Extract Participations information.
X = df['Participations'].loc[df['Participations']>0].values

# Print
print(X)
# array([ 5387, 23618,  1710, ...,    16,    21,     0], dtype=int64)

# Make fit
results = bl.fit(X)

# Plot
bl.plot(title="Benford's Law for Participations")

# My Final considerations

Wow! As you could see all number have passed the Benford's law validation with no anomaly detected. 
I need to mention that "Drawn" has a more of the digit 2 then was expect and because this it almost have not passed the test with the statistic result of only 0.09, but as the minimum limiar was of 0.05 it has also passed.

Finally, I can say that acording with the Benford's law, all the data collected by Ivan Gottardo is correct. So I would like to say a big thank for Ivan and congratulation on this amazing job.
Unfortunately, I have to accept that my favorite team is not the all time best one for while.