# NumPy Exercises

This kernel uses exercises of NumPy from the Machine Learning Plus webpage --> https://www.machinelearningplus.com/python/101-numpy-exercises-python/

This kernel is part of my 100 days of machine learning challenge.
Check out my progress on this challenge --> https://github.com/themlphdstudent/100DaysofMachineLearning

## <font color='red'> <center> I am continuously updating this kernel. </center> </font>

## <font color='red'> <center> Don't forget to upvote. </center> </font>

# Table of Content
- [Import required libraries](import_required_libraries)
- [*Exercise 51*. How to generate one-hot encodings for an array in numpy?](#51)
- [*Exercise 52*. How to create row numbers grouped by a categorical variable?](#52)
- [*Exercise 53*. How to create groud ids based on a given categorical variable?](#53)
- [*Exercise 54*. How to rank items in an array using numpy?](#54)
- [*Exercise 55*. How to rank items in a multidimensional array using numpy?](#55)
- [*Exercise 56*. How to find the maximum value in each row of a numpy array 2d?](#56)
- [*Exercise 57*. How to compute the min-by-max for each row for a numpy array 2d?](#57)
- [*Exercise 58*. How to find the duplicate records in a numpy array?](#58)
- [*Exercise 59*. How to find the grouped mean in numpy?](#59)
- [*Exercise 60*. How to convert a PIL image to numpy array?](#60)
- [*Exercise 61*. How to drop all missing values from a numpy array?](#61)
- [*Exercise 62*. How to compute the euclidean distance between two arrays?](#62)
- [*Exercise 63*. How to find all the local maxima (or peaks) in a 1d array?](#63)
- [*Exercise 64*. How to subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?](#64)
- [*Exercise 65*. How to find the index of n'th repetition of an item in an array](#65)
- [*Exercise 66*. How to convert numpy's datetime64 object to datetime's datetime object?](#66)
- [*Exercise 67*. How to compute the moving average of a numpy array?](#67)
- [*Exercise 68*. How to create a numpy array sequence given only the starting point, length and the step?](#68)
- [*Exercise 69*. How to fill in missing dates in an irregular series of numpy dates?](#69)
- [*Exercise 70*. How to create strides from a given 1D array?](#70)

<a id='import_required_libraries'></a>
## Import required libraries
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# importing the core library
import numpy as np

# print multiple output in single cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

<a id='51'></a>
### *Exercise 51*. How to generate one-hot encodings for an array in numpy?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question: Compute the one-hot encodings (dummy binary variables for each unique value in the array)
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

np.array([[1 if i == j else 0 for i in list(set(arr))] for j in arr])

<a id='52'></a>
### *Exercise 52*. How to create row numbers grouped by a categorical variable?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question: Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.

species = np.genfromtxt("../input/iris/Iris.csv", delimiter=',', dtype='str', usecols=5, skip_header=1)
species_small = np.sort(np.random.choice(species, size=20))
species_small

[i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])]

<a id='53'></a>
### *Exercise 53*. How to create groud ids based on a given categorical variable?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question: Create group ids based on a given categorical variable. Use the following sample from iris species as input.



<a id='54'></a>
### *Exercise 54*. How to rank items in an array using numpy? 
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question: Create the ranks for the given numeric array a.

<a id='55'></a>
### *Exercise 55*. How to rank items in a multidimensional array using numpy?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question: Create a rank array of the same shape as a given numeric array a.


<a id='56'></a>
### *Exercise 56*. How to find the maximum value in each row of a numpy array 2d?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question: Compute the maximum for each row in the given array.



<a id='57'></a>
### *Exercise 57*. How to compute the min-by-max for each row for a numpy array 2d?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question: Compute the min-by-max for each row for given 2d numpy array.

<a id='58'></a>
### *Exercise 58*. How to find the duplicate records in a numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question: Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.


<a id='59'></a>
### *Exercise 59*. How to find the grouped mean in numpy?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question: Find the mean of a numeric column grouped by a categorical column in a 2D numpy array
iris = np.genfromtxt("../input/iris/Iris.csv", delimiter=',', dtype='object', skip_header=1)
sepallength = iris[:,1].astype(float)
targets = iris[:,5]
[[target, np.mean(sepallength[np.where(targets == target)])] for target in np.unique(targets)]

<a id='60'></a>
### *Exercise 60*. How to convert a PIL image to numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question: Import the image from the following URL and convert it to a numpy array.

from PIL import Image
I = Image.open("../input/exercise60/Denali_Mt_McKinley.jpg")
np.array(I)

<a id='61'></a>
### *Exercise 61*. How to drop all missing values from a numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question:

<a id='62'></a>
### *Exercise 62*. How to compute the euclidean distance between two arrays?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question:

<a id='63'></a>
### *Exercise 63*. How to find all the local maxima (or peaks) in a 1d array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question:

<a id='64'></a>
### *Exercise 64*. How to subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question:

<a id='65'></a>
### *Exercise 65*. How to find the index of n'th repetition of an item in an array
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question:

<a id='66'></a>
### *Exercise 66*. How to convert numpy's `datetime64` object to datetime's `datetime` object?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question:

<a id='67'></a>
### *Exercise 67*. How to compute the moving average of a numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question:

<a id='68'></a>
### *Exercise 68*. How to create a numpy array sequence given only the starting point, length and the step?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question: Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

#end = len * step + starting point
end = (10 * 3) + 5

np.arange(5, end, 3)

<a id='69'></a>
### *Exercise 69*. How to fill in missing dates in an irregular series of numpy dates?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
# Question:

<a id='20'></a>
### *Exercise 70*. How to create strides from a given 1D array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [ ]:
arr = np.arange(15) 
arr

# Desired Output
# > [[ 0  1  2  3]
# >  [ 2  3  4  5]
# >  [ 4  5  6  7]
# >  [ 6  7  8  9]
# >  [ 8  9 10 11]
# >  [10 11 12 13]]

# Solution

print(np.array([arr[i:i+4]for i in range(0,12,2)]))   