In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
sns.set()

In [4]:
raw_data = pd.read_csv("../input/diabetes-dataset/traning dataset diabetes.csv")
raw_data

Pregnancies  Glucose   ...     Age  Outcome
0              6      148   ...      50        1
1              1       85   ...      31        0
2              8      183   ...      32        1
3              1       89   ...      21        0
4              0      137   ...      33        1
5              5      116   ...      30        0
6              3       78   ...      26        1
7             10      115   ...      29        0
8              2      197   ...      53        1
9              8      125   ...      54        1
10             4      110   ...      30        0
11            10      168   ...      34        1
12            10      139   ...      57        0
13             1      189   ...      59        1
14             5      166   ...      51        1
15             7      100   ...      32        1
16             0      118   ...      31        1
17             7      107   ...      31        1
18             1      103   ...      33        0
19             1      115   ...      32        1
20             3      126   ...      27        0
21             8       99   ...      50        0
22             7      196   ...      41        1
23             9      119   ...      29        1
24            11      143   ...      51        1
25            10      125   ...      41        1
26             7      147   ...      43        1
27             1       97   ...      22        0
28            13      145   ...      57        0
29             5      117   ...      38        0
..           ...      ...   ...     ...      ...
588            3      176   ...      52        1
589            0       73   ...      25        0
590           11      111   ...      45        1
591            2      112   ...      24        0
592            3      132   ...      44        1
593            2       82   ...      25        0
594            6      123   ...      34        0
595            0      188   ...      22        1
596            0       67   ...      46        0
597            1       89   ...      21        0
598            1      173   ...      38        1
599            1      109   ...      26        0
600            1      108   ...      24        0
601            6       96   ...      28        0
602            1      124   ...      30        0
603            7      150   ...      54        1
604            4      183   ...      36        1
605            1      124   ...      21        0
606            1      181   ...      22        1
607            1       92   ...      25        0
608            0      152   ...      27        0
609            1      111   ...      23        0
610            3      106   ...      24        0
611            3      174   ...      36        1
612            7      168   ...      40        1
613            6      105   ...      26        0
614           11      138   ...      50        1
615            3      106   ...      27        0
616            6      117   ...      30        0
617            2       68   ...      23        0

[618 rows x 9 columns]

Outcome is independent i.e. it is "y" and rest are independent variables

In [5]:
y = raw_data['Outcome']
x1 = raw_data[['Pregnancies', 'Glucose', 'BloodPressure','SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction','Age']]

x = sm.add_constant(x1)
logistic_reg = sm.Logit(y,x)
result = logistic_reg.fit()

result.summary()


Optimization terminated successfully.
         Current function value: 0.466427
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  618
Model:                          Logit   Df Residuals:                      609
Method:                           MLE   Df Model:                            8
Date:                Sat, 08 Jun 2019   Pseudo R-squ.:                  0.2770
Time:                        07:21:06   Log-Likelihood:                -288.25
converged:                       True   LL-Null:                       -398.68
                                        LLR p-value:                 2.540e-43
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -8.6308      0.822    -10.506      0.000     -10.241      -7.021
Pregnancies                  0.1231      0.036      3.432      0.001       0.053       0.193
Glucose                      0.0330      0.004      8.180      0.000       0.025       0.041
BloodPressure               -0.0109      0.006     -1.883      0.060      -0.022       0.000
SkinThickness               -0.0024      0.008     -0.308      0.758      -0.017       0.013
Insulin                     -0.0008      0.001     -0.845      0.398      -0.003       0.001
BMI                          0.1033      0.017      5.988      0.000       0.069       0.137
DiabetesPedigreeFunction     1.0747      0.336      3.195      0.001       0.415       1.734
Age                          0.0100      0.010      0.954      0.340      -0.011       0.030
============================================================================================
"""

In [6]:
np.set_printoptions(formatter = {'float': lambda x: "{0:0.2f}".format(x)})
result.predict()

array([0.68, 0.05, 0.76, 0.04, 0.92, 0.14, 0.07, 0.62, 0.66, 0.02, 0.25,
       0.90, 0.78, 0.61, 0.57, 0.37, 0.42, 0.20, 0.36, 0.24, 0.43, 0.33,
       0.94, 0.27, 0.69, 0.41, 0.74, 0.05, 0.46, 0.29, 0.40, 0.57, 0.05,
       0.04, 0.39, 0.14, 0.66, 0.38, 0.18, 0.58, 0.72, 0.73, 0.10, 0.94,
       0.58, 0.96, 0.42, 0.04, 0.39, 0.02, 0.03, 0.08, 0.06, 0.80, 0.70,
       0.02, 0.87, 0.42, 0.86, 0.20, 0.01, 0.51, 0.03, 0.28, 0.35, 0.11,
       0.20, 0.52, 0.03, 0.28, 0.21, 0.34, 0.84, 0.27, 0.06, 0.00, 0.09,
       0.24, 0.67, 0.09, 0.09, 0.00, 0.14, 0.05, 0.73, 0.20, 0.50, 0.20,
       0.77, 0.07, 0.02, 0.27, 0.37, 0.24, 0.25, 0.50, 0.08, 0.02, 0.13,
       0.51, 0.85, 0.26, 0.06, 0.03, 0.28, 0.25, 0.02, 0.38, 0.11, 0.11,
       0.58, 0.71, 0.05, 0.11, 0.71, 0.52, 0.35, 0.18, 0.12, 0.05, 0.90,
       0.28, 0.16, 0.30, 0.15, 0.59, 0.49, 0.19, 0.20, 0.14, 0.60, 0.70,
       0.65, 0.29, 0.05, 0.24, 0.10, 0.07, 0.27, 0.20, 0.13, 0.33, 0.17,
       0.38, 0.46, 0.00, 0.06, 0.32, 0.59, 0.04, 0.

In [7]:
np.array(raw_data['Outcome'])

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [8]:
result.pred_table()

array([[361.00, 43.00],
       [86.00, 128.00]])

In [9]:
confusion_matrix = pd.DataFrame(result.pred_table())
confusion_matrix.columns = ['Predicted No Diabetes', 'Predicted Diabetes']
confusion_matrix = confusion_matrix.rename(index = {0 : 'Actual No Diabetes', 1 : 'Actual Diabetes'})
confusion_matrix

Predicted No Diabetes  Predicted Diabetes
Actual No Diabetes                  361.0                43.0
Actual Diabetes                      86.0               128.0

In [10]:
cm = np.array(confusion_matrix)
training_accuracy = (cm[0,0] + cm[1,1])/ cm.sum()
training_accuracy

0.7912621359223301

Testing Model

In [11]:
test_data = pd.read_csv("../input/diabetes-dataset/test dataset diabetes.csv")
test_data

Pregnancies  Glucose   ...     Age  Outcome
0              9      112   ...      50        1
1              0      119   ...      24        1
2              2      112   ...      28        0
3              2       92   ...      28        0
4              6      183   ...      45        0
5              0       94   ...      21        0
6              2      108   ...      21        0
7              4       90   ...      29        0
8              0      125   ...      21        0
9              0      132   ...      21        0
10             5      128   ...      45        0
11             4       94   ...      21        0
12             7      114   ...      34        1
13             0      102   ...      24        0
14             2      111   ...      23        0
15             1      128   ...      22        0
16            10       92   ...      31        0
17            13      104   ...      38        1
18             5      104   ...      48        0
19             2       94   ...      23        0
20             7       97   ...      32        1
21             1      100   ...      28        0
22             0      102   ...      27        0
23             4      128   ...      24        0
24             6      147   ...      50        1
25             4       90   ...      31        0
26             3      103   ...      27        0
27             2      157   ...      30        0
28             1      167   ...      33        1
29             0      179   ...      22        1
..           ...      ...   ...     ...      ...
120            2       99   ...      21        0
121            1      102   ...      42        1
122           11      120   ...      48        1
123            3      102   ...      26        0
124            1      109   ...      22        0
125            9      140   ...      45        1
126           13      153   ...      39        0
127           12      100   ...      46        0
128            1      147   ...      27        1
129            1       81   ...      32        0
130            3      187   ...      36        1
131            6      162   ...      50        1
132            4      136   ...      22        1
133            1      121   ...      28        0
134            3      108   ...      25        0
135            0      181   ...      26        1
136            8      154   ...      45        1
137            1      128   ...      37        1
138            7      137   ...      39        0
139            0      123   ...      52        1
140            1      106   ...      26        0
141            6      190   ...      66        1
142            2       88   ...      22        0
143            9      170   ...      43        1
144            9       89   ...      33        0
145           10      101   ...      63        0
146            2      122   ...      27        0
147            5      121   ...      30        0
148            1      126   ...      47        1
149            1       93   ...      23        0

[150 rows x 9 columns]

In [12]:
test_cleaned = test_data['Outcome']
test_data = test_data.drop(['Outcome'], axis = 1)
test_data = sm.add_constant(test_data)

In [13]:
def confusion_matrix(data, actual_values, model):
    predicted_values = model.predict(data)
    bins = np.array ([0, 0.5, 1])
    cm = np.histogram2d(actual_values, predicted_values, bins = bins)[0]
    accuracy = (cm[0,0] + cm[1,1])/cm.sum()
    return cm, accuracy

In [14]:
conf_matrix = confusion_matrix(test_data, test_cleaned, result)
conf_matrix

(array([[86.00, 10.00],
        [25.00, 29.00]]), 0.7666666666666667)

In [15]:
confusion_matrix = pd.DataFrame(conf_matrix[0])
confusion_matrix.columns = ['Predicted No Diabetes', 'Predicted Diabetes']
confusion_matrix = confusion_matrix.rename(index = {0 : 'Actual No Diabetes', 1 : 'Actual Diabetes'})
confusion_matrix

Predicted No Diabetes  Predicted Diabetes
Actual No Diabetes                   86.0                10.0
Actual Diabetes                      25.0                29.0