# Основы NumPy. Часть 1

Заполните ячейки предложенного блокнота.

- Подключите библиотеку **NumPy** под псевдонимом **np**.

In [2]:
import numpy as np


- Проверьте номер версии этой библиотеки.

In [3]:
np.__version__



'1.16.3'

- Создайте одномерный массив размерности 10, заполненный нулями.
- Поменяйте значение пятого элемента массива на 1.
- Поменяйте значения трёх последних элементов массива на 2 (одним действием).

In [ ]:
A = np.zeros(10)
A

In [ ]:
A[4]=1
A

In [ ]:
A[-3:]=2
A

- Создайте выборку (одномерный массив) значений роста для 100 человек из равномерного распределения на отрезке $[150; 200]$. 
- Найдите средний рост людей по выборке ($\mu$).
- Найдите стандартное отклонение роста по выборке ($\sigma$).
- Какой процент людей в выборке имеют рост в диапазоне $[\mu-3\sigma; \mu+3\sigma]$?
- Удалите "аномальные" (не подчиняющиеся правилу выше) значения роста из выборки.

In [ ]:
x = np.random.uniform(150,200,100)
x

In [ ]:
x.mean()

In [ ]:
x.std()


In [ ]:
s = x[(x.mean()-x.std()<x)&(x.mean()+x.std()>x)]
s1=s.size/x.size
s1

- Создайте равномерную сетку из 20 точек на отрезке $\left[0; \frac{\pi}{2}\right]$.
- Проверьте для каждой точки выполнение тригонометрического тождества $\cos\alpha = \sin\left(\frac{\pi}{2}-\alpha\right)$. Для этого: а) создайте массив $\cos\alpha$; б) создайте массив $\sin\left(\frac{\pi}{2}-\alpha\right)$; в) создайте логическую функцию **close(x, y, eps)**, которая возвращает **True**, если $|x-y|<\varepsilon$, и **False** в противном случае; г) примените данную функцию к двум массивам, созданным выше; д) убедитесь, что все значения в полученном массиве равны **True**.

In [4]:
d = np.linspace(0,np.pi/2,20)
d


array([0.        , 0.08267349, 0.16534698, 0.24802047, 0.33069396,
       0.41336745, 0.49604095, 0.57871444, 0.66138793, 0.74406142,
       0.82673491, 0.9094084 , 0.99208189, 1.07475538, 1.15742887,
       1.24010236, 1.32277585, 1.40544935, 1.48812284, 1.57079633])

In [5]:
w =np.cos(d)
w

array([1.00000000e+00, 9.96584493e-01, 9.86361303e-01, 9.69400266e-01,
       9.45817242e-01, 9.15773327e-01, 8.79473751e-01, 8.37166478e-01,
       7.89140509e-01, 7.35723911e-01, 6.77281572e-01, 6.14212713e-01,
       5.46948158e-01, 4.75947393e-01, 4.01695425e-01, 3.24699469e-01,
       2.45485487e-01, 1.64594590e-01, 8.25793455e-02, 6.12323400e-17])

In [6]:
y=np.sin(np.pi/2 - d)
y

array([1.        , 0.99658449, 0.9863613 , 0.96940027, 0.94581724,
       0.91577333, 0.87947375, 0.83716648, 0.78914051, 0.73572391,
       0.67728157, 0.61421271, 0.54694816, 0.47594739, 0.40169542,
       0.32469947, 0.24548549, 0.16459459, 0.08257935, 0.        ])

In [7]:
w-y

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.11022302e-16, 1.11022302e-16,
       0.00000000e+00, 1.11022302e-16, 0.00000000e+00, 0.00000000e+00,
       1.11022302e-16, 5.55111512e-17, 5.55111512e-17, 5.55111512e-17,
       5.55111512e-17, 5.55111512e-17, 5.55111512e-17, 6.12323400e-17])

In [8]:
def close(x,y,eps):
    if np.abs(x-y)<eps:
        return True
    else:
        return False
    

In [ ]:
close (w,y,1e-6)

In [ ]:
np.abs(w - y)<0.1

In [ ]:
close_v = np.vectorize(close)
close_v(w,y,1e-6)

In [10]:
x = np.random.normal(5, 2.5, (10, 5))
x

array([[ 7.26611309,  4.78037656,  2.27003061,  5.2826974 ,  2.69867069],
       [ 0.74250607,  7.82507762,  1.4937247 ,  1.4877173 ,  9.81941747],
       [ 8.2164511 ,  8.0415551 ,  3.25127969,  6.01547421,  4.31856839],
       [ 4.82292116,  5.66672224,  4.93794132,  4.24319795,  6.14273519],
       [ 7.31603931,  3.62042013,  2.14324677,  3.46638246,  5.98051115],
       [11.54545402,  1.93242941,  5.58447753, -0.36836515,  2.6694127 ],
       [ 4.23569346,  4.64785494,  3.46998803,  3.81827071,  2.0812315 ],
       [ 8.43149895,  0.64624275,  5.00247526,  5.70633389,  1.71632019],
       [ 1.52870025,  6.80819497,  3.34420429,  5.39550276,  7.93582078],
       [ 3.13549052,  1.70458609,  1.84625864,  4.19811754,  8.00495569]])

In [11]:
a = x[4,:].mean()
a

4.505319964515333

In [12]:
s = np.median(x[:,3])
s

4.220657742457842

In [ ]:
print(np.sum(x, axis=1)) 
print(np.mean(x, axis=0)) 
print(np.sum(x)) 

In [ ]:
print(x[:3, :3])

In [ ]:
y = np.sum(x, axis = 1)#cyмма эл
print(y)
a = np.mean(y) #средняя сумм
print(a)
print(y[y < a])
s = np.array(y[y < a]) 
print(s.size)


In [ ]:
w = (x[x[:, 0]>x[: ,-1 ]])
print(w)
print(w.ndim, w.shape)
    

In [ ]:
y = np.sum(x, axis = 1) #сумма эл строки
a = np.mean(x , axis = 1)  #средняя сумма
s  = x[y > a]
print(s)
print(np.linalg.matrix_rank(s))

- Загрузите матрицу из файла **cardio_train.csv** (файл уже подключен к этому блокноту и находится в директории '../input'). Первую строку файла --- заголовок --- не считываем.
- Найдите размеры полученной матрицы.
- Второй столбец полученной матрицы обозначает возраст пациентов (в днях). Переведите возраст в года, поделив на 365.25 и округлив вниз до ближайшего целого. Замените соответствующий столбец в матрице.
- Каково количество пациентов старше 50 лет?
- Третий столбец матрицы означает пол пациента (1 --- женщина, 2 --- мужчина). Четвёртый столбец соответствует росту. Верно ли, что средний рост мужчин больше среднего роста женщин?
- Пятый столбец означает вес человека. Каковы минимальный и максимальный вес в выборке? Какое количество людей имеют максимальный вес?
- Каково количество некурящих людей (значение в четвёртом с конца столбце равно 0), у которых обнаружены сердечно-сосудистые заболевания (значение в последнем столбце равно 1)?

In [ ]:
df = np.loadtxt('../input/cardio_train.csv', delimiter=';', skiprows=1)
print(df.shape)

In [ ]:
x = df[:,1]
y = x / 365.25
s = np.floor(y)
print(s)
df[:,1] = s

In [ ]:
k = (s[s>50])
print(k.size)

In [ ]:
women_height =  df[df[:, 2]==1, 3]
men_height = df[df[:, 2]==2, 3]
w = np.mean(women_height)
m =  np.mean(men_height)
print(w<m, w , m)

In [ ]:
f = df[:,4]
mmax = np.max(f)
mmin = np.min(f)
g = (f[f == mmin])
print(mmax, mmin,g.size)

In [ ]:
k =  df[df[:, -4]==0 & (df[:, -1]==1)].shape[0]
print(k)
