In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['petrol-consumption', 'bank-note-authentication-uci-data']


# Random Forest Regression

* Question: How to predict the gas consumption (in millions of gallons) in 48 of the US states based on petrol tax (in cents), per capita income (dollars), paved highways (in miles) and the proportion of population with the driving license.

* Source: Historical Petral Consumption 

* Solution: Using random forest algorithm via the Scikit-Learn Python library. 

In [13]:
data = pd.read_csv('../input/petrol-consumption/petrol_consumption.csv') 

In [14]:
data.head()

Petrol_tax         ...          Petrol_Consumption
0         9.0         ...                         541
1         9.0         ...                         524
2         9.0         ...                         561
3         7.5         ...                         414
4         8.0         ...                         410

[5 rows x 5 columns]

In [15]:
X = data.iloc[:, 0:4].values  
y = data.iloc[:, 4].values  

In [16]:
# import sklearn 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=0)  

In [17]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)  

In [18]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)  
regressor.fit(X_train, y_train)  
y_pred = regressor.predict(X_test)  

In [19]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))  

Mean Absolute Error: 54.583333333333336
Mean Squared Error: 4469.795833333334
Root Mean Squared Error: 66.85653171780102


In [20]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=100, random_state=0)  
regressor.fit(X_train, y_train)  
y_pred = regressor.predict(X_test)  

In [21]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))  

Mean Absolute Error: 54.68866666666667
Mean Squared Error: 4124.747753333334
Root Mean Squared Error: 64.22419912566707


# Random Forest Classification 

* Question: How to predict whether a bank currency note is authentic or not based on four attributes i.e. variance of the image wavelet transformed image, skewness, entropy, and curtosis of the image.

* Source: UCI Machine Learning Database 

* Solution: Using random forest algorithm for a binary classfication. 

In [54]:
data = pd.read_csv('../input/bank-note-authentication-uci-data/BankNote_Authentication.csv')

In [55]:
data.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [56]:
X = data.iloc[:, 0:4].values  
y = data.iloc[:, 4].values 

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)  

In [45]:
sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)  

In [50]:
from sklearn.ensemble import RandomForestClassifier 
rf_model = RandomForestClassifier(n_estimators=20, random_state=0)  
rf_model.fit(X_train, y_train)  
y_pred = rf_model.predict(X_test)  

In [51]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))  

[[229   3]
 [  2 178]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       232
           1       0.98      0.99      0.99       180

   micro avg       0.99      0.99      0.99       412
   macro avg       0.99      0.99      0.99       412
weighted avg       0.99      0.99      0.99       412

0.9878640776699029


In [52]:
rf_model2 = RandomForestClassifier(n_estimators=100, random_state=0)  
rf_model2.fit(X_train, y_train)  
y_pred = rf_model2.predict(X_test)  

In [53]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))  

[[229   3]
 [  1 179]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       232
           1       0.98      0.99      0.99       180

   micro avg       0.99      0.99      0.99       412
   macro avg       0.99      0.99      0.99       412
weighted avg       0.99      0.99      0.99       412

0.9902912621359223


In [58]:
# alternative way to write the feature and label dataset 
X = data.drop('class', axis = 1)
y = data['class']

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)  

In [61]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
clt = DecisionTreeClassifier()
clt.fit(X_train, y_train)
y_pred = clt.predict(X_test)

In [62]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))  

[[226   6]
 [  3 177]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       232
           1       0.97      0.98      0.98       180

   micro avg       0.98      0.98      0.98       412
   macro avg       0.98      0.98      0.98       412
weighted avg       0.98      0.98      0.98       412

0.9781553398058253
