In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

from subprocess import check_output
print(check_output(["ls", "../input"]).decode("utf8"))

# Any results you write to the current directory are saved as output.

Pokemon.csv



In [2]:
import numpy as np
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [5]:
np.arange(1,20,3, dtype=np.float64)

array([ 1.,  4.,  7., 10., 13., 16., 19.])

In [6]:
x = np.array([1,3,5,7])

In [7]:
type(x)

numpy.ndarray

In [8]:
np.array([(1,3,5),(7,9,11),(13,15,17)]).ndim

2

In [9]:
np.zeros((2,3), dtype=np.int16)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [10]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [11]:
np.random.random((3,3))

array([[0.84749405, 0.35665115, 0.55455765],
       [0.03038966, 0.32539703, 0.61759898],
       [0.21569324, 0.90742156, 0.44442924]])

In [12]:
threeD = np.arange(1,30,2).reshape(3,5)
print(threeD)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]


In [13]:
threeD.itemsize

8

In [14]:
a = np.arange(5)
b = np.array([2,3,4,6,7])
a

array([0, 1, 2, 3, 4])

In [15]:
diff = a-b
diff

array([-2, -2, -2, -3, -3])

In [16]:
b**2

array([ 4,  9, 16, 36, 49])

In [17]:
2*b

array([ 4,  6,  8, 12, 14])

In [18]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [19]:
np.sum(a)

10

In [20]:
np.max(b)

7

In [21]:
np.min(b)

2

In [22]:
b>2

array([False,  True,  True,  True,  True])

In [23]:
a*b

array([ 0,  3,  8, 18, 28])

In [24]:
x = np.array([[1,1],[0,1]])
y = np.array([[2,0],[3,4]])
x*y

array([[2, 0],
       [0, 4]])

In [25]:
x.dot(y)

array([[5, 4],
       [3, 4]])

In [26]:
x.sum()

3

In [27]:
x.sum(axis=0)

array([1, 2])

In [28]:
z = np.random.random((3,4))
z

array([[0.58307673, 0.91831363, 0.11894934, 0.43310524],
       [0.45029451, 0.537263  , 0.59927399, 0.9361197 ],
       [0.91081919, 0.54433485, 0.14581021, 0.35536973]])

In [29]:
np.mean(z)

0.5443941762198515

In [30]:
np.median(z)

0.5407989249093115

In [31]:
np.std(z)

0.2628265630166465

In [32]:
data_set = np.random.random((2,3))
data_set

array([[0.30565496, 0.23940519, 0.45363754],
       [0.53212107, 0.10846372, 0.08703995]])

In [33]:
np.reshape(data_set, (3,2))

array([[0.30565496, 0.23940519],
       [0.45363754, 0.53212107],
       [0.10846372, 0.08703995]])

In [34]:
np.reshape(data_set, (6))

array([0.30565496, 0.23940519, 0.45363754, 0.53212107, 0.10846372,
       0.08703995])

In [35]:
np.ravel(data_set)

array([0.30565496, 0.23940519, 0.45363754, 0.53212107, 0.10846372,
       0.08703995])

In [36]:
ds = np.random.random((5,10))
ds

array([[0.46293693, 0.37319895, 0.72202634, 0.88489016, 0.66674887,
        0.96947567, 0.1200245 , 0.32225817, 0.83953804, 0.03869679],
       [0.76863612, 0.28325429, 0.9767856 , 0.45155828, 0.94774326,
        0.09766194, 0.24529188, 0.03753548, 0.85245435, 0.50717846],
       [0.97426603, 0.80915972, 0.89387021, 0.25155303, 0.83686143,
        0.30546432, 0.96020994, 0.76854003, 0.72878177, 0.73020483],
       [0.48797898, 0.99598236, 0.16041208, 0.70517452, 0.20472925,
        0.90921636, 0.17670463, 0.68922466, 0.77418734, 0.50129299],
       [0.67551032, 0.48344272, 0.88674286, 0.14206955, 0.84737805,
        0.91435476, 0.78698353, 0.47805323, 0.79007468, 0.58233561]])

In [37]:
ds[1]

array([0.76863612, 0.28325429, 0.9767856 , 0.45155828, 0.94774326,
       0.09766194, 0.24529188, 0.03753548, 0.85245435, 0.50717846])

In [38]:
ds[1][1]

0.283254291375854

In [39]:
ds[1,0]

0.7686361214318215

In [40]:
ds[1:3]

array([[0.76863612, 0.28325429, 0.9767856 , 0.45155828, 0.94774326,
        0.09766194, 0.24529188, 0.03753548, 0.85245435, 0.50717846],
       [0.97426603, 0.80915972, 0.89387021, 0.25155303, 0.83686143,
        0.30546432, 0.96020994, 0.76854003, 0.72878177, 0.73020483]])

In [41]:
ds[1:3,0]

array([0.76863612, 0.97426603])

In [42]:
ds[::2]

array([[0.46293693, 0.37319895, 0.72202634, 0.88489016, 0.66674887,
        0.96947567, 0.1200245 , 0.32225817, 0.83953804, 0.03869679],
       [0.97426603, 0.80915972, 0.89387021, 0.25155303, 0.83686143,
        0.30546432, 0.96020994, 0.76854003, 0.72878177, 0.73020483],
       [0.67551032, 0.48344272, 0.88674286, 0.14206955, 0.84737805,
        0.91435476, 0.78698353, 0.47805323, 0.79007468, 0.58233561]])