In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../input/winequality-red.csv")

data.head()

fixed acidity  volatile acidity   ...     alcohol  quality
0            7.4              0.70   ...         9.4        5
1            7.8              0.88   ...         9.8        5
2            7.8              0.76   ...         9.8        5
3           11.2              0.28   ...         9.8        6
4            7.4              0.70   ...         9.4        5

[5 rows x 12 columns]

In [3]:
data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [4]:
data.corr()

fixed acidity    ...      quality
fixed acidity              1.000000    ...     0.124052
volatile acidity          -0.256131    ...    -0.390558
citric acid                0.671703    ...     0.226373
residual sugar             0.114777    ...     0.013732
chlorides                  0.093705    ...    -0.128907
free sulfur dioxide       -0.153794    ...    -0.050656
total sulfur dioxide      -0.113181    ...    -0.185100
density                    0.668047    ...    -0.174919
pH                        -0.682978    ...    -0.057731
sulphates                  0.183006    ...     0.251397
alcohol                   -0.061668    ...     0.476166
quality                    0.124052    ...     1.000000

[12 rows x 12 columns]

In [5]:
list(data)

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [6]:
x = data[['fixed acidity',
 'volatile acidity',
 'citric acid',
 'chlorides',
 'total sulfur dioxide',
 'density',
 'sulphates',
 'alcohol']]

y = data['quality']

In [7]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Decision Tree

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [10]:
a = clf.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix

print(accuracy_score(y_test,a))
print(confusion_matrix(y_test,a))

0.625
[[ 0  0  1  0  0  0]
 [ 0  1 10  1  0  0]
 [ 0  3 95 29  2  1]
 [ 0  4 31 84  5  1]
 [ 0  0  3 22 18  2]
 [ 0  0  1  3  1  2]]


# Random Forest

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
clf = RandomForestClassifier()
clf.fit(x_train,y_train)
a = clf.predict(x_test)

/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [13]:
print(accuracy_score(y_test,a))
print(confusion_matrix(y_test,a))

0.68125
[[  0   0   1   0   0   0]
 [  0   0   9   3   0   0]
 [  0   1 106  23   0   0]
 [  0   1  25  95   4   0]
 [  0   0   3  26  16   0]
 [  0   0   0   4   2   1]]
